# Generated by Django 4.1.5 on 2023-02-01 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_requested",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 2, 1, 12, 52, 53, 880106),
                    ),
                ),
                ("employee_name", models.TextField()),
                ("is_sick", models.BooleanField()),
                ("is_personal", models.BooleanField()),
                ("is_paid", models.BooleanField()),
                ("is_approved", models.BooleanField(blank=True, default=False)),
                ("approved_by", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
